"""The build ledger, generated by code from the contract and the verification spec (rule 1):
one row per unit to implement and one per property to test, each with an owner, the files it
may write, what it covers, and what done means."""

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ..spec.base import Artifact


class TaskRow(Artifact):
    id: str  # T-NNNN
    kind: Literal["B", "T", "F"] = Field(
        description="B build a unit, T test a property, F fix after a ruling"
    )
    owner: str = Field(description="the role that writes it")
    produces: str
    writes: list[str] = Field(description="the only files this row may write")
    covers: list[str] = Field(description="clause or property ids")
    depends: list[str] = Field(default_factory=list)
    done_when: str
    status: Literal["todo", "doing", "built", "verified", "blocked", "superseded"] = "todo"


class Tasks(Artifact):
    rows: list[TaskRow]

    def by_kind(self, kind: str) -> list[TaskRow]:
        return [r for r in self.rows if r.kind == kind]
