"""The null implementation, generated from the contract's typed units (rule 7; RELIABILITY
D3b): every unit returns its declared return type's zero value. Nobody authors it, so nobody
can fit a test to it; a test that passes against it is vacuous."""

from __future__ import annotations

import re

from ..artifacts.contract import Contract, Unit

_ZERO = {
    "str": '""',
    "int": "0",
    "float": "0.0",
    "bool": "False",
    "bytes": 'b""',
    "None": "None",
    "NoneType": "None",
    "list": "[]",
    "dict": "{}",
    "set": "set()",
    "tuple": "()",
    "frozenset": "frozenset()",
    "Any": "None",
    "object": "None",
}


def zero_of(type_expr: str) -> str:
    t = type_expr.strip()
    if not t:
        return "None"
    if "|" in t:
        parts = [p.strip() for p in t.split("|")]
        non_null = [p for p in parts if p not in ("None", "NoneType")]
        return zero_of(non_null[0]) if non_null else "None"
    m = re.match(r"^(Optional|typing\.Optional)\[(.+)\]$", t)
    if m:
        return "None"
    head = re.match(r"^([A-Za-z_][A-Za-z0-9_.]*)", t)
    name = head.group(1).split(".")[-1] if head else t
    if name in _ZERO:
        return _ZERO[name]
    if name in ("List", "Sequence", "Iterable", "Iterator", "Generator"):
        return "[]"
    if name in ("Dict", "Mapping"):
        return "{}"
    if name in ("Set",):
        return "set()"
    if name in ("Tuple",):
        return "()"
    return "None"


def _sig(u: Unit) -> str:
    ps = []
    for p in u.params:
        s = f"{p.name}: {p.type}" if p.type else p.name
        if p.default is not None:
            s += f" = {p.default}"
        ps.append(s)
    return ", ".join(ps)


def null_module(contract: Contract) -> str:
    """The stub module's source. Functions return zeros; a class gets its methods."""
    L = [
        f'"""Null implementation of block {contract.block!r}: every unit returns its zero value.',
        "Generated by code from the contract; nobody authors it (rule 7).",
        '"""',
        "from __future__ import annotations",
        "",
    ]
    classes: dict[str, list[Unit]] = {}
    for u in contract.units:
        if u.kind == "class":
            classes.setdefault(u.name, [])
        elif u.kind == "method" and "." in u.name:
            cls, _ = u.name.split(".", 1)
            classes.setdefault(cls, []).append(u)
    for u in contract.units:
        if u.kind == "function":
            L.append(f"def {u.name}({_sig(u)}) -> {u.returns or 'None'}:")
            L.append(f"    return {zero_of(u.returns)}")
            L.append("")
    for cls, methods in classes.items():
        L.append(f"class {cls}:")
        L.append("    def __init__(self, *args, **kwargs):")
        L.append("        pass")
        L.append("")
        for m in methods:
            _, meth = m.name.split(".", 1)
            sig = _sig(m)
            L.append(f"    def {meth}(self{', ' + sig if sig else ''}) -> {m.returns or 'None'}:")
            L.append(f"        return {zero_of(m.returns)}")
            L.append("")
    return "\n".join(L).rstrip() + "\n"
