"""The harness figure: how the runtime is wired (the second block diagram in the README). Same
glass idiom as the workflow figure (figure.py); generated by code so it cannot drift from the
modules it names (rule 4)."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from .figure import ACTORS, ARROW, ARROW_W, FONT, FOOT, MUTED, TEXT, W, Box, _esc, rgba

Theme = Literal["dark", "light"]

# The two bands are the point of this figure: the recipe is a project (its own repo, a package the
# harness discovers); everything under it is the template, installed as a dependency.
# (label, y0, y1, rgb)
BANDS = [
    ("THE PROJECT · a recipe package in its own repo", 112, 218, (163, 113, 247)),
    ("THE TEMPLATE · the harness, installed as a package", 246, 1016, (139, 148, 158)),
]
# (kind, x, y, w, h, lines)
BOXES = [
    ("you", 120, 34, 420, 50, ["TaskSpec · the start page, or a task.json handed in"]),
    (
        "both",
        60,
        146,
        880,
        60,
        ["recipe · stages · prompts · schemas · fixtures · checks · walk legs · the workflow figure"],
    ),
    (
        "code",
        60,
        280,
        880,
        96,
        ["driver · code decides every step", "next · done · undo · halt as a report · resume from disk"],
    ),
    ("a", 60, 422, 270, 72, ["author side", "Claude · anthropic · agent sdk · claude -p"]),
    ("b", 365, 422, 270, 72, ["checker side", "Codex · codex exec · litellm"]),
    ("code", 670, 422, 270, 72, ["fake backend", "the offline walk · zero tokens"]),
    (
        "freeze",
        200,
        542,
        600,
        54,
        ["ask() · one schema per call · re-ask with the exact problems · never a tool"],
    ),
    (
        "code",
        60,
        644,
        420,
        72,
        ["events.jsonl · the one owner", "state.json · artifacts/vNNN.json · gates/ · review/"],
    ),
    ("both", 520, 644, 420, 72, ["MLflow · a sink", "spans per step and call · tokens per role · evals"]),
    ("code", 60, 762, 270, 54, ["Prefect · wraps the loop · cancel"]),
    ("code", 365, 762, 270, 54, ["monitor.db · the runs index"]),
    ("code", 670, 762, 270, 54, ["view model · built from the files"]),
    ("you", 300, 862, 400, 54, ["Reflex page · rail · gates · evidence"]),
    ("output", 390, 962, 220, 50, ["your browser"]),
]
ARROWS = [
    (500, 84, 500, 144, False),
    (500, 206, 500, 278, False),
    (500, 376, 195, 420, False),
    (500, 376, 500, 420, False),
    (500, 376, 805, 420, False),
    (195, 494, 380, 540, False),
    (500, 494, 500, 540, False),
    (805, 494, 620, 540, False),
    (500, 596, 270, 642, False),
    (480, 680, 518, 680, True),
    (270, 716, 195, 760, False),
    (270, 716, 500, 760, False),
    (270, 716, 805, 760, False),
    (500, 816, 500, 860, False),
    (805, 816, 640, 860, False),
    (500, 916, 500, 960, False),
]
FOOT_LINES = [
    "The project owns what the workflow is; the template owns how any workflow runs.",
    "One owner per fact: state.json owns status, events.jsonl owns what happened, the pydantic class owns every shape.",
    "MLflow, Prefect and monitor.db are sinks and views; nothing the driver needs is read back from them.",
    "The fake backend answers every schema offline, so every branch is walked before a token is spent.",
]


def render(theme: Theme = "dark", names: dict[str, str] | None = None) -> str:
    names = names or {"a": "Claude", "b": "Codex"}
    text, muted, foot, arrow, aw = TEXT[theme], MUTED[theme], FOOT[theme], ARROW[theme], ARROW_W[theme]
    H = 962 + 50 + 14 + 24 * (len(FOOT_LINES) - 1) + 26
    L = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" font-family="{FONT}">',
        "<defs>",
        f'<marker id="ah" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{arrow}"/></marker>',
        f'<marker id="ah-rev" viewBox="0 0 10 10" refX="1" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M10,0 L0,5 L10,10 z" fill="{arrow}"/></marker>',
        "</defs>",
    ]
    if theme == "light":
        L.append(f'<rect width="{W}" height="{H}" rx="22" fill="#ffffff"/>')
    else:
        L.append("<!-- transparent canvas: the host page's dark ground shows through -->")
    from .figure import LIGHT_FILL, MARKS, _box_style, _data_uri

    for label, y0, y1, rgb in BANDS:
        L.append(
            f'<rect x="40" y="{y0}" width="920" height="{y1 - y0}" rx="18" fill="{rgba(rgb, 0.05)}" stroke="{rgba(rgb, 0.55)}" stroke-width="1.5" stroke-dasharray="7 6"/>'
        )
        L.append(
            f'<text x="62" y="{y0 + 22}" font-size="13" font-weight="600" letter-spacing="1.5" fill="{muted}">{_esc(label)}</text>'
        )

    for kind, x, y, w, h, lines in BOXES:
        b = Box(
            x,
            y,
            w,
            h,
            kind,
            [ln.replace("Claude", names["a"]).replace("Codex", names["b"]) for ln in lines],
            weight=700 if kind == "freeze" else 600,
            size=18 if len(lines) > 1 else 19,
        )
        fill, stroke, sw = _box_style(b, theme)
        if theme == "light" and kind in ("a", "b", "you", "both", "code"):
            fill = LIGHT_FILL[kind]
        stroke_attr = f' stroke="{stroke}" stroke-width="{sw}"' if stroke != "none" else ""
        L.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="{fill}"{stroke_attr}/>')
        n = len(b.lines)
        for i, ln in enumerate(b.lines):
            cy = y + h / 2 + (i - (n - 1) / 2) * 24
            color = "#ffffff" if (kind == "freeze" and theme == "dark") else text
            glyph = ""
            dx = 0.0
            if i == 0 and kind in ("a", "b"):
                mark = MARKS[kind]
                if mark.exists():  # the side's mark, as on the page
                    L.append(
                        f'<image href="{_data_uri(mark)}" x="{x + w / 2 - 70:g}" y="{cy - 11:.1f}" width="22" height="22"/>'
                    )
                    dx = 12.0
                elif theme == "dark":
                    glyph = f'<tspan fill="{ACTORS[kind][2]}">{ACTORS[kind][1]} </tspan>'
            size = b.size if i == 0 else 15
            col = color if i == 0 else muted
            L.append(
                f'<text x="{x + w / 2 + dx:g}" y="{cy:.1f}" text-anchor="middle" dominant-baseline="central" font-size="{size}" font-weight="{b.weight if i == 0 else 500}" fill="{col}">{glyph}{_esc(ln)}</text>'
            )
    for x1, y1, x2, y2, both in ARROWS:
        extra = ' marker-start="url(#ah-rev)"' if both else ""
        L.append(
            f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{arrow}" stroke-width="{aw}" stroke-linecap="round" marker-end="url(#ah)"{extra}/>'
        )
    # legend
    legend = [
        ("a", names["a"], 650, 24),
        ("b", names["b"], 650, 50),
        ("you", "You", 650, 76),
        ("both", "Sink", 770, 24),
        ("code", "Code — no model", 770, 50),
    ]
    for kind, label, x, y in legend:
        rgb = ACTORS[kind][0]
        L.append(
            f'<rect x="{x}" y="{y}" width="26" height="18" rx="6" fill="{rgba(rgb, 0.22) if theme == "dark" else LIGHT_FILL[kind]}"'
            + (f' stroke="{rgba(rgb, 0.75)}" stroke-width="1.2"' if theme == "dark" else "")
            + "/>"
        )
        L.append(
            f'<text x="{x + 36}" y="{y + 9}" dominant-baseline="central" font-size="15" fill="{muted}">{_esc(label)}</text>'
        )
    fy = H - 26 - 24 * (len(FOOT_LINES) - 1)
    for i, ln in enumerate(FOOT_LINES):
        L.append(
            f'<text x="500" y="{fy + 24 * i}" text-anchor="middle" dominant-baseline="central" font-size="16" font-style="italic" fill="{foot}">{_esc(ln)}</text>'
        )
    L.append("</svg>")
    return "\n".join(L) + "\n"


def write(out: Path, theme: Theme = "dark") -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(theme), encoding="utf-8")
    return out
