"""The harness figure: how the runtime is wired (the second block diagram in the README). Same
glass idiom as the workflow figure (figure.py); generated by code so it cannot drift from the
modules it names (rule 4)."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from .figure import ACTORS, ARROW, ARROW_W, FONT, FOOT, MUTED, TEXT, W, Box, _esc, rgba

Theme = Literal["dark", "light"]

# (kind, x, y, w, h, lines)
BOXES = [
    ("you", 390, 34, 220, 50, ["TaskSpec · the start page"]),
    (
        "code",
        60,
        130,
        880,
        96,
        ["driver · code decides every step", "next · done · undo · halt as a report · resume from disk"],
    ),
    ("a", 60, 272, 270, 72, ["author side", "Claude · anthropic · agent sdk · claude -p"]),
    ("b", 365, 272, 270, 72, ["checker side", "Codex · codex exec · litellm"]),
    ("code", 670, 272, 270, 72, ["fake backend", "the offline walk · zero tokens"]),
    (
        "freeze",
        200,
        392,
        600,
        54,
        ["ask() · one schema per call · re-ask with the exact problems · never a tool"],
    ),
    (
        "code",
        60,
        494,
        420,
        72,
        ["events.jsonl · the one owner", "state.json · artifacts/vNNN.json · gates/ · review/"],
    ),
    ("both", 520, 494, 420, 72, ["MLflow · a sink", "spans per step and call · tokens per role · evals"]),
    ("code", 60, 612, 270, 54, ["Prefect · a task per step · cancel"]),
    ("code", 365, 612, 270, 54, ["monitor.db · the runs index"]),
    ("code", 670, 612, 270, 54, ["view model · built from the files"]),
    ("you", 300, 712, 400, 54, ["Reflex page · rail · NOW · gates · evidence"]),
    ("output", 390, 812, 220, 50, ["your browser"]),
]
ARROWS = [
    (500, 84, 500, 128, False),
    (500, 226, 195, 270, False),
    (500, 226, 500, 270, False),
    (500, 226, 805, 270, False),
    (195, 344, 380, 390, False),
    (500, 344, 500, 390, False),
    (805, 344, 620, 390, False),
    (500, 446, 270, 492, False),
    (480, 530, 518, 530, True),
    (270, 566, 195, 610, False),
    (270, 566, 500, 610, False),
    (270, 566, 805, 610, False),
    (500, 666, 500, 710, False),
    (805, 666, 640, 710, False),
    (500, 766, 500, 810, False),
]
FOOT_LINES = [
    "One owner per fact: state.json owns status, events.jsonl owns what happened, the pydantic class owns every shape.",
    "MLflow, Prefect and monitor.db are sinks and views; nothing the driver needs is read back from them.",
    "The fake backend answers every schema offline, so every branch is walked before a token is spent.",
]


def render(theme: Theme = "dark", names: dict[str, str] | None = None) -> str:
    names = names or {"a": "Claude", "b": "Codex"}
    text, muted, foot, arrow, aw = TEXT[theme], MUTED[theme], FOOT[theme], ARROW[theme], ARROW_W[theme]
    H = 812 + 50 + 14 + 24 * (len(FOOT_LINES) - 1) + 26
    L = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" font-family="{FONT}">',
        "<defs>",
        f'<marker id="ah" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{arrow}"/></marker>',
        f'<marker id="ah-rev" viewBox="0 0 10 10" refX="1" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M10,0 L0,5 L10,10 z" fill="{arrow}"/></marker>',
        "</defs>",
    ]
    if theme == "light":
        L.append(f'<rect width="{W}" height="{H}" rx="22" fill="#ffffff"/>')
    else:
        L.append("<!-- transparent canvas: the host page's dark ground shows through -->")
    from .figure import LIGHT_FILL, _box_style

    for kind, x, y, w, h, lines in BOXES:
        b = Box(
            x,
            y,
            w,
            h,
            kind,
            [ln.replace("Claude", names["a"]).replace("Codex", names["b"]) for ln in lines],
            weight=700 if kind == "freeze" else 600,
            size=18 if len(lines) > 1 else 19,
        )
        fill, stroke, sw = _box_style(b, theme)
        if theme == "light" and kind in ("a", "b", "you", "both", "code"):
            fill = LIGHT_FILL[kind]
        stroke_attr = f' stroke="{stroke}" stroke-width="{sw}"' if stroke != "none" else ""
        L.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="{fill}"{stroke_attr}/>')
        n = len(b.lines)
        for i, ln in enumerate(b.lines):
            cy = y + h / 2 + (i - (n - 1) / 2) * 24
            color = "#ffffff" if (kind == "freeze" and theme == "dark") else text
            glyph = ""
            if i == 0 and kind in ("a", "b") and theme == "dark":
                glyph = f'<tspan fill="{ACTORS[kind][2]}">{ACTORS[kind][1]} </tspan>'
            size = b.size if i == 0 else 15
            col = color if i == 0 else muted
            L.append(
                f'<text x="{x + w / 2:g}" y="{cy:.1f}" text-anchor="middle" dominant-baseline="central" font-size="{size}" font-weight="{b.weight if i == 0 else 500}" fill="{col}">{glyph}{_esc(ln)}</text>'
            )
    for x1, y1, x2, y2, both in ARROWS:
        extra = ' marker-start="url(#ah-rev)"' if both else ""
        L.append(
            f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{arrow}" stroke-width="{aw}" stroke-linecap="round" marker-end="url(#ah)"{extra}/>'
        )
    # legend
    legend = [
        ("a", names["a"], 650, 24),
        ("b", names["b"], 650, 50),
        ("you", "You", 650, 76),
        ("both", "Sink", 770, 24),
        ("code", "Code — no model", 770, 50),
    ]
    for kind, label, x, y in legend:
        rgb = ACTORS[kind][0]
        L.append(
            f'<rect x="{x}" y="{y}" width="26" height="18" rx="6" fill="{rgba(rgb, 0.22) if theme == "dark" else LIGHT_FILL[kind]}"'
            + (f' stroke="{rgba(rgb, 0.75)}" stroke-width="1.2"' if theme == "dark" else "")
            + "/>"
        )
        L.append(
            f'<text x="{x + 36}" y="{y + 9}" dominant-baseline="central" font-size="15" fill="{muted}">{_esc(label)}</text>'
        )
    fy = H - 26 - 24 * (len(FOOT_LINES) - 1)
    for i, ln in enumerate(FOOT_LINES):
        L.append(
            f'<text x="500" y="{fy + 24 * i}" text-anchor="middle" dominant-baseline="central" font-size="16" font-style="italic" fill="{foot}">{_esc(ln)}</text>'
        )
    L.append("</svg>")
    return "\n".join(L) + "\n"


def write(out: Path, theme: Theme = "dark") -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(theme), encoding="utf-8")
    return out
