"""The harness figure: how the runtime is wired, the second block diagram in the README. It is
the user's architecture sketch (docs: "Python-First Agent Workflow Dashboard") drawn in the same
glass idiom as the workflow figure: the agent workflow feeds Prefect and MLflow, both feed
monitor.db, then Reflex, the custom dashboard, the browser. The responsibility split that
accompanies the sketch is text in the README, not part of the figure. Generated by code so it
cannot drift (rule 4)."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from .figure import ARROW, ARROW_W, FONT, MUTED, TEXT, W, Box, _esc, rgba

Theme = Literal["dark", "light"]

# one hue per node, the workflow figure's palette plus rose; nothing shares a colour
HUES = {
    "blue": ((77, 143, 220), "#6ea6e8", "#dbe3ee"),
    "gold": ((187, 128, 9), "#d69a26", "#fbf0c4"),
    "violet": ((154, 110, 224), "#b28ae8", "#e6e2f5"),
    "teal": ((47, 163, 154), "#43bdb2", "#d4efe8"),
    "rose": ((232, 99, 159), "#e8639f", "#f9dbe8"),
    "red": ((208, 74, 69), "#e06661", "#fbe1cc"),
    "slate": ((139, 148, 158), "#9aa4ae", "#e9e9e9"),
}
TITLE, SUB, ITEM = 26, 18, 18  # font sizes
LEAD = 27.0  # line height inside a box
PAD = 32.0  # top and bottom padding inside a box
GAP = 52.0  # between rows, room for the arrow


def _h(lines: list[str]) -> float:
    return PAD * 2 + LEAD * (len(lines) - 1)


WORKFLOW = ["AGENT WORKFLOW", "the workflow figure above · Python"]
PREFECT = [
    "PREFECT",
    "Python SDK",
    "",
    "orchestration",
    "flow/task state",
    "dependencies",
    "retries",
    "failures",
    "scheduling",
    "cancellation",
]
MLFLOW = [
    "MLFLOW",
    "Python SDK",
    "",
    "agent traces",
    "spans",
    "LLM calls",
    "tool calls",
    "retrieval",
    "tokens / cost",
    "latency",
    "evaluations",
    "ML experiments",
    "params / metrics",
    "artifacts/models",
]
MONITOR = [
    "monitor.db",
    "SQLite",
    "",
    "dashboard-only state",
    "- agent progress",
    "- current activity",
    "- UI labels",
    "- custom messages",
    "- graph positions",
    "- selected run state",
]
REFLEX = [
    "REFLEX",
    "Python App",
    "",
    "task creation",
    "run controls",
    "live monitoring",
    "traces",
    "experiments",
    "evaluations",
    "artifacts",
]
DASHBOARD = [
    "CUSTOM DASHBOARD",
    "",
    "Overview",
    "Workflow DAG",
    "Agent status",
    "MLflow traces",
    "Experiments",
    "Evaluations",
    "Artifacts",
    "Costs / tokens",
    "Live activity",
    "Errors",
]


def layout() -> list[Box]:
    """(x, y, w, h, hue, lines); y flows down with one gap per row."""
    boxes: list[Box] = []
    y = 30.0
    boxes.append(Box(60, y, 880, _h(WORKFLOW), "blue", WORKFLOW))
    y += _h(WORKFLOW) + GAP
    hp, hm = _h(PREFECT), _h(MLFLOW)
    boxes.append(Box(70, y, 400, hp, "gold", PREFECT))
    boxes.append(Box(530, y, 400, hm, "violet", MLFLOW))
    y += max(hp, hm) + GAP
    for hue, lines in (("teal", MONITOR), ("rose", REFLEX), ("red", DASHBOARD)):
        boxes.append(Box(240, y, 520, _h(lines), hue, lines))
        y += _h(lines) + GAP
    boxes.append(Box(360, y, 280, 62, "slate", ["Browser"]))
    return boxes


def render(theme: Theme = "dark", names: dict[str, str] | None = None) -> str:  # noqa: ARG001
    text, muted, arrow, aw = TEXT[theme], MUTED[theme], ARROW[theme], ARROW_W[theme]
    boxes = layout()
    H = int(boxes[-1].y + boxes[-1].h + 30)
    L = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" font-family="{FONT}">',
        "<defs>",
        f'<marker id="ah" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{arrow}"/></marker>',
        "</defs>",
    ]
    if theme == "light":
        L.append(f'<rect width="{W}" height="{H}" rx="22" fill="#ffffff"/>')
    else:
        L.append("<!-- transparent canvas: the host page's dark ground shows through -->")
    for b in boxes:
        rgb, label, flat = HUES[b.kind]
        if theme == "dark":
            fill, stroke = rgba(rgb, 0.14), rgba(rgb, 0.7)
        else:
            fill, stroke = flat, "none"
        stroke_attr = f' stroke="{stroke}" stroke-width="1.5"' if stroke != "none" else ""
        L.append(
            f'<rect x="{b.x:g}" y="{b.y:g}" width="{b.w:g}" height="{b.h:g}" rx="16" fill="{fill}"{stroke_attr}/>'
        )
        n = len(b.lines)
        for i, ln in enumerate(b.lines):
            if not ln:
                continue
            cy = b.y + PAD + i * LEAD if n > 1 else b.y + b.h / 2
            title = i == 0
            size = TITLE if title else (SUB if i == 1 else ITEM)
            weight = 700 if title else (600 if i == 1 else 500)
            col = (label if theme == "dark" else text) if title else (text if i == 1 else muted)
            L.append(
                f'<text x="{b.x + b.w / 2:g}" y="{cy:.1f}" text-anchor="middle" dominant-baseline="central" font-size="{size}" font-weight="{weight}" fill="{col}">{_esc(ln)}</text>'
            )
    top, pre, ml, mon, ref, dash, browser = boxes

    def seg(x1, y1, x2, y2):
        L.append(
            f'<line x1="{x1:g}" y1="{y1:g}" x2="{x2:g}" y2="{y2:g}" stroke="{arrow}" stroke-width="{aw}" stroke-linecap="round" marker-end="url(#ah)"/>'
        )

    cx, yb = top.x + top.w / 2, top.y + top.h + 2
    for b in (pre, ml):  # fan-out
        seg(cx, yb, b.x + b.w / 2, b.y - 2)
    for b in (pre, ml):  # fan-in
        seg(b.x + b.w / 2, b.y + b.h + 2, mon.x + mon.w / 2, mon.y - 2)
    for a, b in ((mon, ref), (ref, dash), (dash, browser)):
        seg(a.x + a.w / 2, a.y + a.h + 2, b.x + b.w / 2, b.y - 2)
    L.append("</svg>")
    return "\n".join(L) + "\n"


def write(out: Path, theme: Theme = "dark") -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(theme), encoding="utf-8")
    return out
