"""The layers figure: the ten layers of the production agentic workflow as one block diagram,
in the glass idiom of the workflow figure, alive. Two rows of three: the request path runs
left to right across the top (L1 → L2 → L3), turns down, and back right to left below
(L4 → L6 → L5); under them three thin bands for the planes that touch every layer (L9
authorization, L10 guardrails, L8 observability), and L7 the record as the floor. Every box has
an icon drawn in its own hue; every arrow is dashed and marches; the icons idle (the runtime's
ring turns, the gear turns, the observability trace redraws, the lock rocks). Pure SVG with
SMIL, no script, so a README renders it. Generated by code so it cannot drift from the README's
table (rule 4): the same names, the same tools."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from .figure import ARROW, ARROW_W, FONT, TEXT, W, _esc, rgba

Theme = Literal["dark", "light"]

HUES = {  # one hue per box, vibrant and distinct, no two hot ones touching; planes yellow, floor teal
    "violet": ((124, 92, 255), "#a894ff", "#e8e2ff"),
    "pink": ((236, 72, 153), "#f472b6", "#fbdcec"),
    "red": ((239, 68, 68), "#f87171", "#fddede"),
    "orange": ((249, 115, 22), "#fb923c", "#ffe4cc"),
    "blue": ((59, 130, 246), "#7ab4fb", "#dbeafe"),
    "cyan": ((6, 182, 212), "#22d3ee", "#cff5fb"),
    "yellow": ((234, 179, 8), "#facc15", "#fef3c7"),
    "teal": ((20, 184, 166), "#2dd4bf", "#ccfbf1"),
}


@dataclass
class Box:
    key: str
    title: str
    tools: str
    what: str
    hue: str
    icon: str
    x: float = 0
    y: float = 0
    w: float = 0
    h: float = 0

    @property
    def cx(self) -> float:
        return self.x + self.w / 2

    @property
    def cy(self) -> float:
        return self.y + self.h / 2


@dataclass
class Band:
    key: str
    title: str
    tools: str
    what: str
    hue: str
    icon: str
    y: float = 0
    h: float = 0

    @property
    def cy(self) -> float:
        return self.y + self.h / 2


M = 24.0
GAP = 26.0
BOX_H = 138.0
ROW_GAP = 64.0
BAND_H = 46.0
BAND_GAP = 10.0
FLOOR_H = 60.0
ICON = 34.0  # the icon's box, top-left of a card

TOP = [
    Box("L1", "L1  UI", "Reflex · Jinja2", "what the person sees and decides", "violet", "screen"),
    Box(
        "L2",
        "L2  control plane",
        "MCP SDK · pydantic · Typer · SQLite",
        "the task, the budgets, the registry",
        "pink",
        "sliders",
    ),
    Box(
        "L3",
        "L3  orchestration",
        "the driver · Prefect 3",
        "the next step from disk; detach, cancel, resume",
        "blue",
        "conductor",
    ),
]
BOTTOM = [  # drawn right to left: L4 under L3, L6 under L2, L5 under L1
    Box(
        "L4",
        "L4  agent runtime",
        "Claude Code · Codex · PydanticAI",
        "one model call under a schema",
        "orange",
        "clock",
    ),
    Box(
        "L6",
        "L6  tools",
        "git · pytest · ruff · pyright",
        "the typed registry, every call an event",
        "cyan",
        "wrench",
    ),
    Box(
        "L5", "L5  sandbox", "Docker SDK · Colima", "network off, the run folder the only mount", "red", "box"
    ),
]
PLANES = [
    Band("L9", "L9  authorization", "Cedar", "every step, every write, every tool call", "yellow", "lock"),
    Band(
        "L10",
        "L10  guardrails",
        "Guardrails AI · the schema",
        "before the prompt, after the answer, before a tool call",
        "yellow",
        "shield",
    ),
    Band(
        "L8",
        "L8  observability",
        "MLflow 3 · OpenTelemetry",
        "every event a span, every run evaluated",
        "yellow",
        "pulse",
    ),
]
FLOOR = Band(
    "L7", "L7  state", "files · SQLite · obstore", "the record every layer reads and writes", "teal", "db"
)


def layout() -> tuple[list[Box], list[Box], list[Band], Band, float]:
    bw = (W - 2 * M - GAP * 2) / 3
    y = M
    for i, b in enumerate(TOP):
        b.x, b.y, b.w, b.h = M + i * (bw + GAP), y, bw, BOX_H
    y += BOX_H + ROW_GAP
    for i, b in enumerate(BOTTOM):  # right to left
        b.x, b.y, b.w, b.h = M + (2 - i) * (bw + GAP), y, bw, BOX_H
    y += BOX_H + ROW_GAP
    for p in PLANES:
        p.y, p.h = y, BAND_H
        y += BAND_H + BAND_GAP
    y += 10
    FLOOR.y, FLOOR.h = y, FLOOR_H
    y += FLOOR_H + M
    return TOP, BOTTOM, PLANES, FLOOR, y


def _wrap(text: str, width: int, sep: str = " ") -> list[str]:
    parts, lines, cur = text.split(sep), [], ""
    for part in parts:
        cand = part if not cur else cur + sep + part
        if len(cand) > width and cur:
            lines.append(cur)
            cur = part
        else:
            cur = cand
    lines.append(cur)
    return lines


# ---- the icons: simple strokes in the card's hue, each with one small idle loop ----------------


def icon_svg(kind: str, x: float, y: float, s: float, color: str) -> str:
    """An icon of `kind` in a box of side `s` at (x, y). Strokes only, in the card's colour,
    with an idle loop that never leaves the box."""
    st = f'fill="none" stroke="{color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"'
    g = f'<g transform="translate({x:g},{y:g}) scale({s / 24:g})" {st}>'
    if kind == "screen":  # a monitor whose cursor blinks
        return (
            g
            + '<rect x="2" y="4" width="20" height="13" rx="2"/><path d="M8 21h8M12 17v4"/>'
            + '<path d="M6 8h6M6 11h9"/><rect x="16" y="7" width="2" height="5" fill="'
            + color
            + '" stroke="none">'
            + '<animate attributeName="opacity" values="1;0;1" dur="0.8s" repeatCount="indefinite"/></rect></g>'
        )
    if kind == "sliders":  # three sliders whose knobs drift
        return (
            g
            + '<path d="M3 6h18M3 12h18M3 18h18"/>'
            + '<circle cx="8" cy="6" r="2" fill="'
            + color
            + '"><animate attributeName="cx" values="8;14;8" dur="2s" repeatCount="indefinite"/></circle>'
            + '<circle cx="16" cy="12" r="2" fill="'
            + color
            + '"><animate attributeName="cx" values="16;9;16" dur="2.5s" repeatCount="indefinite"/></circle>'
            + '<circle cx="11" cy="18" r="2" fill="'
            + color
            + '"><animate attributeName="cx" values="11;17;11" dur="3s" repeatCount="indefinite"/></circle></g>'
        )
    if kind == "conductor":  # a conductor: the baton arm beats time, the other arm sways
        return (
            g
            + '<circle cx="12" cy="6" r="3"/>'
            + '<path d="M10.2 11.2l1.8 1 1.8-1v2.4l-1.8-1-1.8 1z" fill="'
            + color
            + '" stroke="none"/>'
            + '<path d="M9.5 13.5L8 22M14.5 13.5L16 22"/>'
            + '<g><path d="M9 13L5.5 9.5 4 5.5"/>'
            + '<animateTransform attributeName="transform" type="rotate" values="0 9 13;9 9 13;0 9 13;-7 9 13;0 9 13" dur="1.2s" repeatCount="indefinite"/></g>'
            + '<g><path d="M15 13l3.5-3.5"/><path d="M18.5 9.5L22.5 2" stroke-width="2.6"/>'
            + '<animateTransform attributeName="transform" type="rotate" values="0 15 13;-28 15 13;0 15 13;18 15 13;0 15 13" dur="1.2s" repeatCount="indefinite"/></g></g>'
        )
    if kind == "clock":  # a clock with an outer arrow that circles it; the minute hand sweeps
        return (
            g
            + '<circle cx="12" cy="12" r="6.2"/>'
            + '<circle cx="12" cy="6.8" r="0.7" fill="'
            + color
            + '" stroke="none"/><circle cx="17.2" cy="12" r="0.7" fill="'
            + color
            + '" stroke="none"/>'
            + '<circle cx="12" cy="17.2" r="0.7" fill="'
            + color
            + '" stroke="none"/><circle cx="6.8" cy="12" r="0.7" fill="'
            + color
            + '" stroke="none"/>'
            + '<path d="M12 12V8.6"/>'
            + '<g><path d="M12 12h3"/><animateTransform attributeName="transform" type="rotate" from="0 12 12" to="360 12 12" dur="4s" repeatCount="indefinite"/></g>'
            + '<g><path d="M12 1.6A10.4 10.4 0 1 1 1.6 12" stroke-width="2.2"/><path d="M9.2 1.2L12.4 1.6 11.6 4.6"/>'
            + '<animateTransform attributeName="transform" type="rotate" from="0 12 12" to="360 12 12" dur="3s" repeatCount="indefinite"/></g></g>'
        )
    if kind == "wrench":  # a wrench that tightens
        return (
            g
            + '<g><path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.6 2.6-2.1-2.1z"/>'
            + '<animateTransform attributeName="transform" type="rotate" values="0 12 12;-14 12 12;0 12 12" dur="1.3s" repeatCount="indefinite"/></g></g>'
        )
    if kind == "box":  # a sealed box whose lid lifts and settles
        return (
            g
            + '<path d="M3 9v9l9 4 9-4V9"/><path d="M12 22V13"/>'
            + '<g><path d="M3 9l9-4 9 4-9 4z"/><animateTransform attributeName="transform" type="translate" values="0 0;0 -1.5;0 0" dur="1.5s" repeatCount="indefinite"/></g></g>'
        )
    if kind == "lock":  # a padlock that rocks
        return (
            g
            + '<g><rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/><circle cx="12" cy="16" r="1.4" fill="'
            + color
            + '" stroke="none"/>'
            + '<animateTransform attributeName="transform" type="rotate" values="0 12 16;-7 12 16;0 12 16;7 12 16;0 12 16" dur="1.8s" repeatCount="indefinite"/></g></g>'
        )
    if kind == "shield":  # a shield whose tick draws itself
        return (
            g
            + '<path d="M12 2l8 3v7c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V5z"/>'
            + '<path d="M8.5 12.5l2.3 2.3L15.5 10" stroke-dasharray="12" stroke-dashoffset="12">'
            + '<animate attributeName="stroke-dashoffset" values="12;0;0;12" keyTimes="0;0.4;0.8;1" dur="1.5s" repeatCount="indefinite"/></path></g>'
        )
    if kind == "pulse":  # a trace that keeps drawing
        return (
            g
            + '<rect x="2" y="4" width="20" height="14" rx="2"/>'
            + '<path d="M4 12h3l2-5 3 10 2-6 2 3h4" stroke-dasharray="40" stroke-dashoffset="40">'
            + '<animate attributeName="stroke-dashoffset" values="40;0" dur="1.2s" repeatCount="indefinite"/></path><path d="M9 21h6"/></g>'
        )
    if kind == "db":  # a cylinder whose rings shimmer
        return (
            g
            + '<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 1.7 3.6 3 8 3s8-1.3 8-3V5"/>'
            + '<path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"><animate attributeName="opacity" values="1;0.3;1" dur="1.5s" repeatCount="indefinite"/></path></g>'
        )
    return g + "</g>"


def render(theme: Theme = "dark") -> str:
    text, arrow, aw = TEXT[theme], ARROW[theme], ARROW_W[theme]
    muted = "#9aa4ae" if theme == "dark" else "#7a7a7a"
    top, bottom, planes, floor, H = layout()
    L = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H:g}" width="{W}" height="{H:g}" font-family="{FONT}">',
        "<defs>",
        f'<marker id="ah" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{arrow}"/></marker>',
        "</defs>",
    ]
    if theme == "light":
        L.append(f'<rect width="{W}" height="{H:g}" rx="22" fill="#ffffff"/>')
    else:
        L.append("<!-- transparent canvas: the host page's dark ground shows through -->")

    def glass(
        x: float,
        y: float,
        w: float,
        h: float,
        hue: str,
        r: int = 16,
        strong: bool = False,
        pulse: bool = False,
    ) -> None:
        rgb, _, flat = HUES[hue]
        if theme == "dark":
            fill = rgba(rgb, 0.18 if strong else 0.10)
            anim = (
                f'<animate attributeName="fill" values="{fill};{rgba(rgb, 0.2)};{fill}" dur="3s" repeatCount="indefinite"/>'
                if pulse
                else ""
            )
            L.append(
                f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{r}" fill="{fill}" stroke="{rgba(rgb, 0.85 if strong else 0.6)}" stroke-width="1.5">{anim}</rect>'
            )
        else:
            L.append(f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{r}" fill="{flat}"/>')

    def label_color(hue: str) -> str:
        return HUES[hue][1] if theme == "dark" else "#4b4b4b"

    def dashed(
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        *,
        dur: str = "0.8s",
        head: bool = True,
        note: str = "",
        note_at: tuple[float, float] | None = None,
        anchor: str = "middle",
        opacity: float = 1.0,
    ) -> None:
        """A marching dashed arrow: the dash offset animates along the line's direction."""
        L.append(
            f'<line x1="{x1:g}" y1="{y1:g}" x2="{x2:g}" y2="{y2:g}" stroke="{arrow}" stroke-width="{aw}" stroke-linecap="round" stroke-dasharray="6 7" opacity="{opacity:g}"'
            + (' marker-end="url(#ah)"' if head else "")
            + f'><animate attributeName="stroke-dashoffset" from="26" to="0" dur="{dur}" repeatCount="indefinite"/></line>'
        )
        if note:
            nx, ny = note_at or ((x1 + x2) / 2, (y1 + y2) / 2 - 8)
            L.append(
                f'<text x="{nx:g}" y="{ny:g}" text-anchor="{anchor}" font-size="12.5" fill="{muted}">{_esc(note)}</text>'
            )

    for b in top + bottom:
        glass(b.x, b.y, b.w, b.h, b.hue, strong=True)
        L.append(icon_svg(b.icon, b.x + 16, b.y + 14, ICON, label_color(b.hue)))
        L.append(
            f'<text x="{b.x + 16 + ICON + 12:g}" y="{b.y + 14 + ICON / 2:g}" dominant-baseline="central" font-size="18" font-weight="700" letter-spacing="0.5" fill="{label_color(b.hue)}">{_esc(b.title.upper())}</text>'
        )
        tl = _wrap(b.tools, 30, sep=" · ")
        y0 = b.y + 14 + ICON + 20
        for k, ln in enumerate(tl[:2]):
            L.append(
                f'<text x="{b.cx:g}" y="{y0 + 18 * k:g}" text-anchor="middle" font-size="14" font-weight="600" fill="{text}">{_esc(ln)}</text>'
            )
        y1 = y0 + 18 * len(tl[:2]) + 6
        for k, ln in enumerate(_wrap(b.what, 36)[:2]):
            L.append(
                f'<text x="{b.cx:g}" y="{y1 + 17 * k:g}" text-anchor="middle" font-size="13" fill="{muted}">{_esc(ln)}</text>'
            )

    # the request path: across the top, down at the right, back across the bottom
    l1, l2, l3 = top
    l4, l6, l5 = bottom
    dashed(l1.x + l1.w + 2, l1.cy, l2.x - 2, l2.cy)
    dashed(l2.x + l2.w + 2, l2.cy, l3.x - 2, l3.cy)
    dashed(
        l3.cx,
        l3.y + l3.h + 2,
        l4.cx,
        l4.y - 2,
        note="the step",
        note_at=(l3.cx + 10, l3.y + l3.h + ROW_GAP / 2 + 4),
        anchor="start",
    )
    dashed(l4.x - 2, l4.cy, l6.x + l6.w + 2, l6.cy)
    dashed(l6.x - 2, l6.cy, l5.x + l5.w + 2, l5.cy)
    # every model call and every tool call goes down through the planes, and comes back answered
    band_top = planes[0].y - 2
    for b, note in ((l4, "every call, through the planes"), (l6, ""), (l5, "")):
        dashed(
            b.cx - 8,
            b.y + b.h + 2,
            b.cx - 8,
            band_top,
            dur="0.6s",
            note=note,
            note_at=(b.cx - 16, b.y + b.h + ROW_GAP / 2 + 4),
            anchor="end",
        )
        dashed(b.cx + 8, band_top, b.cx + 8, b.y + b.h + 2, dur="0.6s", opacity=0.6)
    # the person reads the record: from the floor's left edge, up the margin, round the corner
    # and into L1 -- one path, one arrowhead, never across a card
    xm = 7.0
    r = 6.0
    L.append(
        f'<path d="M{M - 1:g},{floor.cy:g} H{xm + r:g} A{r:g},{r:g} 0 0 1 {xm:g},{floor.cy - r:g} V{l1.cy + r:g} A{r:g},{r:g} 0 0 1 {xm + r:g},{l1.cy:g} H{l1.x - 2:g}" fill="none" stroke="{arrow}" stroke-width="{aw}" stroke-linecap="round" stroke-dasharray="4 8" opacity="0.5" marker-end="url(#ah)"><animate attributeName="stroke-dashoffset" from="24" to="0" dur="1.2s" repeatCount="indefinite"/></path>'
    )
    L.append(
        f'<text x="{xm + 5:g}" y="{l1.y + l1.h + 30:g}" font-size="11.5" fill="{muted}" transform="rotate(-90 {xm + 5:g},{l1.y + l1.h + 30:g})" text-anchor="end">reads the record</text>'
    )
    # the planes: thin bands across the width that breathe, each with its icon
    for p in planes:
        glass(M, p.y, W - 2 * M, p.h, p.hue, r=10, pulse=True)
        L.append(icon_svg(p.icon, M + 12, p.y + (p.h - 26) / 2, 26, label_color(p.hue)))
        L.append(
            f'<text x="{M + 50:g}" y="{p.y + p.h / 2:g}" dominant-baseline="central" font-size="15" font-weight="700" letter-spacing="0.5" fill="{label_color(p.hue)}">{_esc(p.title.upper())}</text>'
        )
        L.append(
            f'<text x="{M + 290:g}" y="{p.y + p.h / 2:g}" dominant-baseline="central" font-size="14" font-weight="600" fill="{text}">{_esc(p.tools)}</text>'
        )
        L.append(
            f'<text x="{W - M - 18:g}" y="{p.y + p.h / 2:g}" dominant-baseline="central" text-anchor="end" font-size="13" fill="{muted}">{_esc(p.what)}</text>'
        )
    # the floor
    glass(M, floor.y, W - 2 * M, floor.h, floor.hue, r=14, strong=True)
    L.append(icon_svg(floor.icon, M + 12, floor.y + (floor.h - 30) / 2, 30, label_color(floor.hue)))
    L.append(
        f'<text x="{M + 54:g}" y="{floor.y + floor.h / 2:g}" dominant-baseline="central" font-size="17" font-weight="700" letter-spacing="0.5" fill="{label_color(floor.hue)}">{_esc(floor.title.upper())}</text>'
    )
    L.append(
        f'<text x="{M + 290:g}" y="{floor.y + floor.h / 2:g}" dominant-baseline="central" font-size="15" font-weight="600" fill="{text}">{_esc(floor.tools)}</text>'
    )
    L.append(
        f'<text x="{W - M - 18:g}" y="{floor.y + floor.h / 2:g}" dominant-baseline="central" text-anchor="end" font-size="13.5" fill="{muted}">{_esc(floor.what)}</text>'
    )
    L.append("</svg>")
    return "\n".join(L) + "\n"


def write(out: Path, theme: Theme = "dark") -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(theme), encoding="utf-8")
    return out
