"""The layers figure: the ten layers of the production agentic workflow as one block diagram,
in the glass idiom of the workflow figure. Left to right the request path (L1 → L2 → L3 → L4),
below it the execution pair a tool call reaches (L6 → L5), then the three planes as thin bands
that touch every layer (L9 authorization, L10 guardrails, L8 observability), and L7 the record
as the floor under everything. Generated by code so it cannot drift from the README's table
(rule 4): the same names, the same tools."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from .figure import ARROW, ARROW_W, FONT, TEXT, W, _esc, rgba

Theme = Literal["dark", "light"]

HUES = {  # one hue per box, vibrant and distinct; the planes light yellow, the floor teal
    "violet": ((124, 92, 255), "#a894ff", "#e8e2ff"),
    "pink": ((236, 72, 153), "#f472b6", "#fbdcec"),
    "red": ((239, 68, 68), "#f87171", "#fddede"),
    "orange": ((249, 115, 22), "#fb923c", "#ffe4cc"),
    "blue": ((59, 130, 246), "#7ab4fb", "#dbeafe"),
    "cyan": ((6, 182, 212), "#22d3ee", "#cff5fb"),
    "yellow": ((234, 179, 8), "#facc15", "#fef3c7"),
    "teal": ((20, 184, 166), "#2dd4bf", "#ccfbf1"),
}


@dataclass
class Box:
    key: str
    title: str
    tools: str
    what: str
    hue: str
    x: float = 0
    y: float = 0
    w: float = 0
    h: float = 0

    @property
    def cx(self) -> float:
        return self.x + self.w / 2

    @property
    def cy(self) -> float:
        return self.y + self.h / 2


@dataclass
class Band:
    key: str
    title: str
    tools: str
    what: str
    hue: str
    y: float = 0
    h: float = 0
    lines: list[str] = field(default_factory=list)


M = 24.0  # the margin
GAP = 22.0  # between boxes in a row
BOX_H = 132.0
ROW_GAP = 70.0  # room for the arrows and their labels
BAND_H = 44.0
BAND_GAP = 10.0
FLOOR_H = 58.0

PATH = [
    Box("L1", "L1  UI", "Reflex · Jinja2", "what the person sees and decides", "violet"),
    Box(
        "L2",
        "L2  control plane",
        "MCP SDK · pydantic · Typer · SQLite",
        "the task, the budgets, the registry",
        "pink",
    ),
    Box(
        "L3",
        "L3  orchestration",
        "the driver · Prefect 3",
        "the next step from disk; detach, cancel, resume",
        "red",
    ),
    Box(
        "L4",
        "L4  agent runtime",
        "Claude Code · Codex · PydanticAI",
        "one model call under a schema",
        "orange",
    ),
]
EXEC = [
    Box("L5", "L5  sandbox", "Docker SDK · Colima", "network off, the run folder the only mount", "blue"),
    Box(
        "L6", "L6  tools", "git · pytest · ruff · pyright", "the typed registry, every call an event", "cyan"
    ),
]
PLANES = [
    Band("L9", "L9  authorization", "Cedar", "every step, every write, every tool call", "yellow"),
    Band(
        "L10",
        "L10  guardrails",
        "Guardrails AI · the schema",
        "before the prompt, after the answer, before a tool call",
        "yellow",
    ),
    Band(
        "L8",
        "L8  observability",
        "MLflow 3 · OpenTelemetry",
        "every event a span, every run evaluated",
        "yellow",
    ),
]
FLOOR = Band("L7", "L7  state", "files · SQLite · obstore", "the record every layer reads and writes", "teal")


def layout() -> tuple[list[Box], list[Box], list[Band], Band, float]:
    bw = (W - 2 * M - GAP * 3) / 4
    y = M
    for i, b in enumerate(PATH):
        b.x, b.y, b.w, b.h = M + i * (bw + GAP), y, bw, BOX_H
    y += BOX_H + ROW_GAP
    # L6 under L4 (a tool call comes down from the runtime), L5 under L3 (L6 hands it to L5)
    l5, l6 = EXEC
    l6.x, l6.y, l6.w, l6.h = PATH[3].x, y, bw, BOX_H
    l5.x, l5.y, l5.w, l5.h = PATH[2].x, y, bw, BOX_H
    y += BOX_H + ROW_GAP - 14
    for p in PLANES:
        p.y, p.h = y, BAND_H
        y += BAND_H + BAND_GAP
    y += 8
    FLOOR.y, FLOOR.h = y, FLOOR_H
    y += FLOOR_H + M
    return PATH, EXEC, PLANES, FLOOR, y


def _wrap(text: str, width: int, sep: str = " ") -> list[str]:
    """Lines no wider than `width` characters, broken at `sep`."""
    parts, lines, cur = text.split(sep), [], ""
    for part in parts:
        cand = part if not cur else cur + sep + part
        if len(cand) > width and cur:
            lines.append(cur)
            cur = part
        else:
            cur = cand
    lines.append(cur)
    return lines


def render(theme: Theme = "dark") -> str:
    text, arrow, aw = TEXT[theme], ARROW[theme], ARROW_W[theme]
    muted = "#9aa4ae" if theme == "dark" else "#7a7a7a"
    path, ex, planes, floor, H = layout()
    L = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H:g}" width="{W}" height="{H:g}" font-family="{FONT}">',
        "<defs>",
        f'<marker id="ah" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{arrow}"/></marker>',
        "</defs>",
    ]
    if theme == "light":
        L.append(f'<rect width="{W}" height="{H:g}" rx="22" fill="#ffffff"/>')
    else:
        L.append("<!-- transparent canvas: the host page's dark ground shows through -->")

    def glass(x: float, y: float, w: float, h: float, hue: str, r: int = 16, strong: bool = False) -> None:
        rgb, _, flat = HUES[hue]
        if theme == "dark":
            L.append(
                f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{r}" fill="{rgba(rgb, 0.18 if strong else 0.10)}" stroke="{rgba(rgb, 0.85 if strong else 0.6)}" stroke-width="1.5"/>'
            )
        else:
            L.append(f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="{r}" fill="{flat}"/>')

    def label_color(hue: str) -> str:
        return HUES[hue][1] if theme == "dark" else "#4b4b4b"

    for b in path + ex:
        glass(b.x, b.y, b.w, b.h, b.hue, strong=True)
        L.append(
            f'<text x="{b.cx:g}" y="{b.y + 30:g}" text-anchor="middle" font-size="18" font-weight="700" letter-spacing="0.5" fill="{label_color(b.hue)}">{_esc(b.title.upper())}</text>'
        )
        # the tools, on one line or two, never past the box's edge
        tl = _wrap(b.tools, 26, sep=" · ")
        for k, ln in enumerate(tl[:2]):
            L.append(
                f'<text x="{b.cx:g}" y="{b.y + 56 + 18 * k:g}" text-anchor="middle" font-size="14" font-weight="600" fill="{text}">{_esc(ln)}</text>'
            )
        y0 = b.y + 56 + 18 * len(tl[:2]) + 8
        for k, ln in enumerate(_wrap(b.what, 34)[:2]):
            L.append(
                f'<text x="{b.cx:g}" y="{y0 + 17 * k:g}" text-anchor="middle" font-size="13" fill="{muted}">{_esc(ln)}</text>'
            )

    def seg(x1: float, y1: float, x2: float, y2: float, note: str = "", above: bool = True) -> None:
        L.append(
            f'<line x1="{x1:g}" y1="{y1:g}" x2="{x2:g}" y2="{y2:g}" stroke="{arrow}" stroke-width="{aw}" stroke-linecap="round" marker-end="url(#ah)"/>'
        )
        if note:
            mx, my = (x1 + x2) / 2, (y1 + y2) / 2
            L.append(
                f'<text x="{mx:g}" y="{my + (-8 if above else 16):g}" text-anchor="middle" font-size="12.5" fill="{muted}">{_esc(note)}</text>'
            )

    # the request path
    for a, b in zip(path, path[1:], strict=False):
        seg(a.x + a.w + 2, a.cy, b.x - 2, b.cy)
    l5, l6 = ex
    l4 = path[3]
    # a tool call: L4 down to L6, then L6 to L5; the planes are on the way, said in words
    seg(l4.cx, l4.y + l4.h + 2, l6.cx, l6.y - 2)
    L.append(
        f'<text x="{l4.cx - 10:g}" y="{l4.y + l4.h + ROW_GAP / 2 + 4:g}" text-anchor="end" font-size="12.5" fill="{muted}">a tool call, through the planes L9 · L10 · L8</text>'
    )
    seg(l6.x - 2, l6.cy, l5.x + l5.w + 2, l5.cy)
    # the planes: thin bands across the width, each touching every layer
    for p in planes:
        glass(M, p.y, W - 2 * M, p.h, p.hue, r=10)
        L.append(
            f'<text x="{M + 18:g}" y="{p.y + p.h / 2:g}" dominant-baseline="central" font-size="15" font-weight="700" letter-spacing="0.5" fill="{label_color(p.hue)}">{_esc(p.title.upper())}</text>'
        )
        L.append(
            f'<text x="{M + 250:g}" y="{p.y + p.h / 2:g}" dominant-baseline="central" font-size="14" font-weight="600" fill="{text}">{_esc(p.tools)}</text>'
        )
        L.append(
            f'<text x="{W - M - 18:g}" y="{p.y + p.h / 2:g}" dominant-baseline="central" text-anchor="end" font-size="13" fill="{muted}">{_esc(p.what)}</text>'
        )
    # the floor
    glass(M, floor.y, W - 2 * M, floor.h, floor.hue, r=14, strong=True)
    L.append(
        f'<text x="{M + 18:g}" y="{floor.y + floor.h / 2:g}" dominant-baseline="central" font-size="17" font-weight="700" letter-spacing="0.5" fill="{label_color(floor.hue)}">{_esc(floor.title.upper())}</text>'
    )
    L.append(
        f'<text x="{M + 250:g}" y="{floor.y + floor.h / 2:g}" dominant-baseline="central" font-size="15" font-weight="600" fill="{text}">{_esc(floor.tools)}</text>'
    )
    L.append(
        f'<text x="{W - M - 18:g}" y="{floor.y + floor.h / 2:g}" dominant-baseline="central" text-anchor="end" font-size="13.5" fill="{muted}">{_esc(floor.what)}</text>'
    )
    L.append("</svg>")
    return "\n".join(L) + "\n"


def write(out: Path, theme: Theme = "dark") -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(theme), encoding="utf-8")
    return out
